# Jekyll Configuration

url: http://www.sunny.in.th #XXX
title: sunny.in.th #XXX
description: Tag line #XXX
author: Somchok Sakjiraphong #XXX
email: s@sunny.in.th #XXX
analytics_id: UA-16137739-1

auto: false
lsi: false
pygments: true
server_port: 4000
markdown: maruku

maruku:
  use_tex: false
  use_divs: false
  png_dir: img/tex
  png_url: /img/tex
